"""add recipient_priority to assignments

Revision ID: 06bec481a52a
Revises: abb98684f5f0
Create Date: 2025-10-17 11:56:15.128103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06bec481a52a'
down_revision = 'abb98684f5f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_priority', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('recipient_priority')

    # ### end Alembic commands ###
