"""add recipient_priority to assignments"""add recipient_priority to assignments



Revision ID: 06bec481a52aRevision ID: 06bec481a52a

Revises: abb98684f5f0Revises: abb98684f5f0

Create Date: 2025-10-17 11:56:15.128103Create Date: 2025-10-17 11:56:15.128103



""""""

from alembic import opfrom alembic import op

import sqlalchemy as saimport sqlalchemy as sa





# revision identifiers, used by Alembic.# revision identifiers, used by Alembic.

revision = '06bec481a52a'revision = '06bec481a52a'

down_revision = 'abb98684f5f0'down_revision = 'abb98684f5f0'

branch_labels = Nonebranch_labels = None

depends_on = Nonedepends_on = None





def upgrade():def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('assignments', schema=None) as batch_op:    with op.batch_alter_table('assignments', schema=None) as batch_op:

        batch_op.add_column(sa.Column('recipient_priority', sa.Boolean(), nullable=True))        batch_op.add_column(sa.Column('recipient_priority', sa.Boolean(), nullable=True))



    # ### end Alembic commands ###    # ### end Alembic commands ###





def downgrade():def downgrade():

    # ### commands auto generated by Alembic - please adjust! ###    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('assignments', schema=None) as batch_op:    with op.batch_alter_table('assignments', schema=None) as batch_op:

        batch_op.drop_column('recipient_priority')        batch_op.drop_column('recipient_priority')



    # ### end Alembic commands ###    # ### end Alembic commands ###

