"""add_deleted_by_and_finished_date_to_notes

Revision ID: 1f9de06bbca4
Revises: 06bec481a52a
Create Date: 2025-10-17 22:17:55.288130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9de06bbca4'
down_revision = '06bec481a52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_note_user', ['note_id', 'user_id'])

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_contact', ['user_id', 'contact_user_id'])

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('finished_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['deleted_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('finished_date')
        batch_op.drop_column('deleted_by')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_contact', type_='unique')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_note_user', type_='unique')

    # ### end Alembic commands ###
