"""remove note status and finished_date add assignment recipient_status and finished_date

Revision ID: 653833f10fe3
Revises: 1f9de06bbca4
Create Date: 2025-10-18 11:31:21.004087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653833f10fe3'
down_revision = '1f9de06bbca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Ajouter les nouveaux champs à assignments
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_status', sa.String(length=20), nullable=False, server_default='en_cours'))
        batch_op.add_column(sa.Column('finished_date', sa.DateTime(), nullable=True))

    # Supprimer les champs obsolètes de notes
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('finished_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Restaurer les champs dans notes
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finished_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='en_cours'))

    # Supprimer les champs de assignments
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('finished_date')
        batch_op.drop_column('recipient_status')
    # ### end Alembic commands ###
